### ISSUE TITLE
"We have reached our daily quota. Please try again tomorrow." - not IP specific

### ISSUE THREAD

**Issue by NSbuilder** [stanford-oval/WikiChat#10]
Not ip specific, seems the quota is low

**Comment by s-jse** [comment]
Due to the high cost of running the demo, we have set a quota per IP address, and also a total quota for all users combined. It seems like we have reached the total quota for today.

**Comment by NSbuilder** [comment]
"It's not a bug - it's a feature"

**Comment by s-jse** [comment]
> "It's not a bug - it's a feature"

Well, it is! 😄 
I increased the daily quota a bit for now.

**Comment by NSbuilder** [comment]
"Most factual" mode is gone with the new interface, impossible to use the gpt 4 version, despite Readme page on the website instructing the use of it
