### ISSUE TITLE
Is there an available API for your project?

### ISSUE THREAD

**Issue by JunyiChE** [stanford-oval/WikiChat#14]
Hi,

This is a very inspiring project, but I wonder if there's an implemented API of this chatbot, so I can process my data. Very unfortunately, my personal computer's hardware may not fit the minimal requirement of running this project locally.

Looking forward to your response

**Comment by s-jse** [comment]
Hi,

Thank you for your interest. Unfortunately, we don't have a hosted API for this project.
But I would love to know what use case you want to try it with, since we are looking into providing some type of API in the future.

**Comment by JunyiChE** [comment]
Hi,

Thank you for your prompt reply. I think one really good use case for your project will be fact verification and generating some golden explanation towards a sample for further use, e.g, enhanced explainability

**Comment by reccea** [comment]
I am equally looking forward to the API for this project.

**Comment by reccea** [comment]
great! thx a lot.
