### ISSUE TITLE
How to retrieve information from Wikipedia in multiple languages?

### ISSUE THREAD

**Issue by Nanshengbeisheng** [stanford-oval/WikiChat#19]
Hello, I have recently been researching WikiChat and noticed that the online demo provided on GitHub can retrieve information from Wikipedia in multiple languages. Could you explain to me how this is achieved? For example, when I ask a question in English, WikiChat may retrieve information from Chinese and Spanish Wikipedia. Does it firstly translate this English question into Chinese by using LLM and then search in the Chinese Wikipedia, or is there another method? I am looking forward to your detailed explanation. Thank you!

**Comment by s-jse** [comment]
Hi,

For retrieving information from multiple languages, we use a multilingual embedding model, specifically, [BAAI/bge-m3](https://huggingface.co/BAAI/bge-m3). Models like this, are trained to find text similarity across languages. For example, an English query can be matched to passages from different languages, without the need to translate the query or passages.

We have just released the code for multilingual retrieval. For your reference, the code for creating the index and retrieving from it is in this folder: https://github.com/stanford-oval/WikiChat/tree/main/retrieval.

We also released a separate search endpoint that you can try. Please refer to its documentation at https://github.com/stanford-oval/WikiChat?tab=readme-ov-file#using-the-free-rate-limited-wikipedia-search-api
