### ISSUE TITLE
How to use other local models

### ISSUE THREAD

**Issue by javyduck** [stanford-oval/WikiChat#2]
Hi, great work for the wikichat! : )

I am wondering how could i use local models like llama2-13B from huggingface for wikichat?

Thanks!

**Comment by s-jse** [comment]
Hi!

Right now, we support models like LLaMA via the Together API. You can set it up by following the instructions at https://github.com/stanford-oval/WikiChat#set-up-the-llm-endpoint. However, using a model like LLaMA-2-13B as is leads to poor results, as it is not good at following our few-shot prompts. So you might have a better shot with higher-quality models like Mistral/Mixtral, or instruction-tuned models.

We are planning to release small distilled (i.e. fine-tuned specifically for WikiChat) models soon, which you can host on a single GPU yourself. These models perform much much better raw LLMs like LLaMA-2, so please stay tuned!

**Comment by s-jse** [comment]
Update: I've added the distilled models I mentioned. You can give them a try!
