### ISSUE TITLE
Database error while saving the current turn.

### ISSUE THREAD

**Issue by StevenXHK** [stanford-oval/WikiChat#3]
Running with Flusk, conversation sometimes only work on first question.
Sample request:
{
    "experiment_id": "test_experiment",
    "dialog_id": "test_dialog",
    "turn_id": 1,
    "system_name": "retrieve_and_generate",
    "engine": "gpt-4",
    "new_user_utterance": "Who's is the us president in 2022?"
}

Error Response:
{
    "agent_utterance": "Database error while saving the current turn.",
    "log_object": {
        "agent_utterance": "Database error while saving the current turn.",
        "combined_evidences": [],
        "combined_utterance": null,
        "draft_engine": null,
        "engine": null,
        "feedback": [],
        "feedback_scores": [],
        "generate_and_correct": {},
        "generate_engine": null,
        "llm_utterance": null,
        "pipeline": "retrieve_and_generate",
        "refined_utterance": null,
        "retrieve_and_generate": {
            "initial_search_bullets": [],
            "initial_search_query": null,
            "initial_search_query_time": null,
            "initial_search_results": []
        },
        "user_utterance": "Who's is the us president in 2022?",
        "wall_time_seconds": 0
    }
}

**Comment by s-jse** [comment]
When saving the current turn, we check that the `(dialog_id, turn_id, system_name)` tuple does not already exist in the database.
This means that the code making requests to the backend needs to generate unique `dialog_id`s and increment that `turn_id` after each turn.
This means when testing the backend code, you cannon send the same request multiple time, as the requests after the first one will result in this error.
