### ISSUE TITLE
Can you share about how to handle table

### ISSUE THREAD

**Issue by shadowinlife** [stanford-oval/WikiChat#36]
Very thanks for this project. I am trying to copy idea to MSD Healthy Book.

Then I found that when I want to index table in html.  The search result is not good enough

**Comment by s-jse** [comment]
Hi,

Thank you for using WikiChat. Would you be able to provide more information about what search index you are using?
In WikiChat, tables are converted to Markdown format first, then indexed. And the search results are always reranked using an LLM call.
