### ISSUE TITLE
Project's default search endpoint not working (https://wikichat.genie.stanford.edu/search)

### ISSUE THREAD

**Issue by AIconicInsight** [stanford-oval/WikiChat#39]
I tested the project in the command line version but the retrieval does not work:
The default search endpoint (https://wikichat.genie.stanford.edu/search) does not allow the used post method, see below. The code uses the POST method, however it seems only the GET method is allowed for this URL.

Also, the endpoint documentation https://wikichat.genie.stanford.edu/search/redoc reroutes to https://wikichat.genie.stanford.edu/, so it cannot be viewed.

Code taken from https://github.com/stanford-oval/WikiChat/blob/main/pipelines/retriever.py#L355-L365 (modified)

**Test endpoint as it is used in the default pipeline:** 
```python
import requests

query_text = "Is tomato a fruit or vegetable?"
retriever_endpoint = "https://wikichat.genie.stanford.edu/search"

evi_num = 20
block_type_limits = {}

response = requests.post(
    retriever_endpoint,
    json={
        "query": [query_text],
        "num_blocks": (
            evi_num + 20 if len(block_type_limits) > 0 else evi_num
        ),  # Retrieve more if we need to limit block types
    },
)
print(f"Status code: {response.status_code}")
print(response.json())
```
Output:
```
Status code: 405
{'detail': 'Method Not Allowed'}
```
---
**Check for allowed methods:** 

```python
response = requests.options("https://wikichat.genie.stanford.edu/search")
print(response.headers.get("Allow"))
```
Output:
```
GET
```

**Comment by s-jse** [comment]
Thank you for reporting this. We have recently changed the search backend API to add new features and corpora. The documentation for that is available at https://search.genie.stanford.edu/redoc. One thing that changed is the URL should be https://search.genie.stanford.edu/wikipedia, but API fields have changed a bit as well.

We will make the necessary changes to this repository soon.

**Comment by AIconicInsight** [comment]
Thanks, works fine now with this endpoint!
