### ISSUE TITLE
Move the back-end URL to an environment variable

### ISSUE THREAD

**Issue by s-jse** [stanford-oval/wikichat#6]
This way, it can be set by different projects without the need to change the code, and also the URL won't be publicly available for everyone to see.

**Comment by george1459** [comment]
yea, simply making the url for [all three files here](https://github.com/stanford-oval/wikichat/tree/main/src/scripts/wiki-llm) an env variable will suffice.

**Comment by s-jse** [comment]
Done. You can now set the backend URL in the `.env.local` file. The caveat is that this environment variable is sent to the client side. This is necessary since the client is the one making the actual HTTP request to the backend.
