### ISSUE TITLE
the big model must be Openai ?

### ISSUE THREAD

**Issue by ucas010** [stanford-oval/WikiChat#6]
with other model is ok ?

**Comment by s-jse** [comment]
Hi,
The best results can be achieved with OpenAI models like `gpt-4` and `gpt-35-turbo-instruct`. However, we do support other models via [Together.ai](https://www.together.ai/) API. Please refer to https://github.com/stanford-oval/WikiChat#set-up-the-llm-endpoint to set this up.

Alternatively, you can host your own open-source model like locally, or download one of our distilled models (to be released soon).
