### ISSUE TITLE
Online demo not working?

### ISSUE THREAD

**Issue by kexul** [stanford-oval/WikiChat#8]
Whatever I typed, it says `Oops! Something went wrong. Please refresh the page and try again.`

**Comment by CxZMoE** [comment]
yes

**Comment by s-jse** [comment]
Thanks for reporting this. Should be fixed now.

**Comment by kexul** [comment]
> Thanks for reporting this. Should be fixed now.

I've tried again, still not working...

**Comment by s-jse** [comment]
I restarted the server, can you please try again?

**Comment by kexul** [comment]
> I restarted the server, can you please try again?

Working now! Thanks!
