### ISSUE TITLE
Extending WikiChat dataset to arXiv + more

### ISSUE THREAD

**Issue by emrgnt-cmplxty** [stanford-oval/WikiChat#9]
I have been working to build an open source search engine for LLMs. It was the inability to control hallucinations in synthetic data creation that led me to want to work on this. I just stumbled upon this paper today and found the magnitude of the improvement quoted to be very impressive.

[The dataset has fully embedded 1.6m Arxiv papers](https://huggingface.co/datasets/SciPhi/AgentSearch-V1) - I'm interested in using this to the WikiChat your approach to include Arxiv and more. 

I'm posting here to see if there are any interested collaborators.

Best,
Owen

**Comment by trivikramak** [comment]
It would be great to have a chat interface for scientific knowledge without the worry of hallucinations!

**Comment by emrgnt-cmplxty** [comment]
Pretty impressed with the responses after hooking up the API, I see it did a number of very interesting queries to reach this conclusion

`User`: "What are some of the most important advances in quantum field theory?"

`Chatbot`: Some of the most important advances in quantum field theory include the understanding of the mathematical structure of correlation functions, the development of the Standard Model, and the discovery of the Higgs boson. However, there are still fundamental questions and a lack of complete mathematical understanding in this field. Recent advances have been made, including the understanding of non-perturbative phenomena, developments in axiomatic quantum field theory, and the creation of effective field theories.
